### PR TITLE
[16.0][MIG] ddmrp_chatter: Migration to 16.0

### PR DESCRIPTION
**Pull request by AlexPForgeFlow**
Migration to 16.0

[ForgeFlow](https://github.com/ForgeFlow)

### CODE REVIEW

**Review by mariadforgeflow — APPROVED** [review]
LGTM!

**Review by BernatPForgeFlow — APPROVED** [review]
LGTM!

**Comment by LoisRForgeFlow** [comment]
Rebased after dependency merge and deleted test requirements.

However, I found that commits history is not complete. @AlexPForgeFlow you need to migrate from the most recent version in which the module is available. This module was in v15 (https://github.com/OCA/ddmrp/commits/15.0/ddmrp_chatter) and you have migrated it from v14. Could you correct this?

**Review by LoisRForgeFlow — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
