### PR TITLE
[13.0][IMP] ddmrp: add execution chart to buffer summary

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**

### CODE REVIEW

**Review by BernatPForgeFlow — APPROVED** [review]
Nice feature! LGTM

**Comment by LoisRForgeFlow** [comment]
Hi @sbidoul 

It seems that this patch failed when being updated to pypi and it is still [not updated in pypi](https://pypi.org/project/odoo13-addon-ddmrp/#history). How could we trigger the upload again?

Thanks

**Comment by sbidoul** [comment]
@LoisRForgeFlow it has been releasedn, but with a pre-release version. You can do a direct push with a commit that bumps the version number to trigger a new release with a round number.

**Comment by LoisRForgeFlow** [comment]
> @LoisRForgeFlow it has been releasedn, but with a pre-release version. You can do a direct push with a commit that bumps the version number to trigger a new release with a round number.

@sbidoul I did that (https://github.com/OCA/ddmrp/commit/9cae277212bcd643ca189454ddfee8f735a8fa5d), but there isn't a new "non-pre" release in pypi: https://pypi.org/project/odoo13-addon-ddmrp/#history

What did I miss?

**Comment by sbidoul** [comment]
IIRC wheels are updated from the main branches nightly, and published immediately when it's merged with ocabot merge bump.

**Comment by LoisRForgeFlow** [comment]
@sbidoul It worked! Thanks!

**Comment by sbidoul** [comment]
The bot should not merge in such case: this is tracked in https://github.com/OCA/oca-github-bot/issues/221 but AFAIK no-one is working on that

**Pull request merged**
