### PR TITLE
[16.0][FIX] ddmrp: Compute chart fields in list view only when click 

### PR DESCRIPTION
**Pull request by BernatPForgeFlow**

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
I think that they are not adding much value, with comparison to the slowdown in performance they produce.
So, for now it is a :+1 for me. @LoisRForgeFlow

**Review by LoisRForgeFlow — COMMENTED** [review]
I think there must be a better compromise, for example, loading the field value only on click of the bubble.

**Review by LoisRForgeFlow — APPROVED** [review]
Much cleaner! :1st_place_medal:

**Pull request merged**
