### PR TITLE
[14.0][FIX] ddmrp: Auto-calculate warehouse when duplicating buffers

### PR DESCRIPTION
**Pull request by BernatPForgeFlow**

### CODE REVIEW

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
Can you also take care that the company is correct? The company of the warehouse/location should be used.

Also, could you take the ocasion to skip the tree view when the duplication result is a single buffer and got to the form view directly?

**Comment by BernatPForgeFlow** [comment]
> Can you also take care that the company is correct? The company of the warehouse/location should be used.
> 
> Also, could you take the ocasion to skip the tree view when the duplication result is a single buffer and got to the form view directly?

Done!

**Review by LoisRForgeFlow — APPROVED** [review]
Ty!

**Pull request merged**
