### PR TITLE
[11.0][FIX] ddmrp: stock warehouse orderpoint buffer zone description

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Seems that weblate adjust incorrectly tab spaces in xml files.
image

After that change I will update description in Weblate.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
It's not Weblate, but using texts spanned across multiple lines in XML file, which Odoo takes literally. Fast-tracking this for your convenience when starting to translate.

**Comment by HviorForgeFlow** [comment]
Translations haven't been update correctly since this PR was merged. At least @oca-travis has updated strings correctly https://github.com/OCA/ddmrp/commit/1ba52546db2f874222e5e70bc2c25d4393285f0b , but in weblate still the same:

https://translation.odoo-community.org/translate/ddmrp-11-0/ddmrp-11-0-ddmrp/es/?checksum=152e138059a5e465
https://translation.odoo-community.org/translate/ddmrp-11-0/ddmrp-11-0-ddmrp/es/?checksum=15968e03b16eef9b
https://translation.odoo-community.org/translate/ddmrp-11-0/ddmrp-11-0-ddmrp/es/?checksum=75fb7118f20d38f3

Any idea @pedrobaeza ?

Thanks,

**Comment by pedrobaeza** [comment]
Not really... @sbidoul when strings are updated following new POT file?

**Comment by sbidoul** [comment]
@pedrobaeza @hveficent there is a plugin in weblate that runs `msgmerge -U` to refresh .po files from .pot. 

The pot files has been correctly updated by oca-travis, as you noted. It has been correctly pulled by weblate.

So for some reason the msgmerge addon did not run or did not do its job.

I made a trivial change to the .pot file at fb0024c34df14f7cf2770e7b4d3cc0478f19ac19 and it was sufficient to trigger the msgmerge run (ceb642b8b1f7910ee3de456fef5d8464b5433c1c).

My guess is that you have been victim of a transient issue on the weblate machine (which is runbot2 which has stability issues these days).

Let me know if you see strange things like this again in the future.

**Pull request merged**
