### PR TITLE
[14.0][MIG] ddmrp_product_replace: Migrate to 14.0

### PR DESCRIPTION
**Pull request by kv1612**

### CODE REVIEW

**Comment by kv1612** [comment]
@ForgeFlow fyi :)

**Comment by LoisRForgeFlow** [comment]
I see pre-commit and readme generation changes ni the migration commit, could you fix that to have a cleaner migration commit?

**Review by LoisRForgeFlow — APPROVED** [review]
Code review, LGTM

**Review by TDu — APPROVED** [review]
LG

**Pull request merged**
