### PR TITLE
[13.0][IMP] ddmrp_packaging: ensure that no inconsistent packaging is entered.

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
... by adding a constraint and by removing the package when the product is changed.

@ForgeFlow

### CODE REVIEW

**Review by jgrandguillaume — APPROVED** [review]
LGTM thx !

**Review by guewen — APPROVED** [review]
/ocabot merge patch

**Comment by LoisRForgeFlow** [comment]
@guewen I'm afraid It does not work with review comments:

/ocabot merge patch

**Pull request merged**
