### PR TITLE
[11.0][FIX] ddmrp: small fixes on readme and adding new icon.

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
* wrong module name on roadmap section.
* Alpeph Objects moved from author sections to initial funders.
* Add new, more odooish icon.

### CODE REVIEW

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Next time please do not delete again the README and put the generic placeholder, as you are generating a very great diff with this. You can leave the old README, and even then, the bot will add the differences with the new auto-generated README from fragments, but the diff will be smaller certainly.

**Comment by LoisRForgeFlow** [comment]
@pedrobaeza Yes,I know but I did that in order to pass travis, as I was having the issue I reported before with de duplicated maintainers target.

**Comment by pedrobaeza** [comment]
Then just remove that line or apply the same patch manually or passing the script locally instead of replacing full file...

**Comment by LoisRForgeFlow** [comment]
@pedrobaeza Oh, good point, that would have been better. Noted for next time!

**Pull request merged**
