### PR TITLE
[11.0][ADD] ddmrp_history

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
* Migrate ddmrp_history from Eficent/ddmrp.
* Add new, more "odooish" description icon.
* Improve tests and minor things code.

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
I have no idea how to remove this warning from runbot:

```
2018-08-01 12:09:23,822 168 WARNING openerp_test py.warnings: /.repo_requirements/virtualenv/python3.5/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
return f(*args, **kwds)
```

From what I saw these warnings related to numpy [are useless](https://github.com/numpy/numpy/pull/432), but I don't know how to make runbot ignore them.

Could someone bring some light?

**Comment by moylop260** [comment]
Hi @lreficent 
Maybe you like to use the ssh connection runbot feature:
 - https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#investigating-travis-test-failures

UPDATED 1:
I just used it and I can reproduce it

 - screen shot 2018-08-03 at 17 04 50

UPDATED 2:
I just installed another version of numpy:
 - `pip install numpy==1.15.0`
And the warning is not raised anymore.

**Comment by LoisRForgeFlow** [comment]
@moylop260 I didn't know it was possible to connect to runbot, that's great! However I am not able to connect:

```
$ ssh -p 8886 -L 18080:localhost:18069 odoo@runbot2.odoo-community.org
ssh_exchange_identification: Connection closed by remote host
```

I have an ssh key associated to this github account. Is there something I'm missing?

Thanks for your help! 

EDIT: tried again (Oct 26) and same issue:
```
$ ssh -p 8562 -L 18080:localhost:18069 odoo@runbot1.odoo-community.org
ssh_exchange_identification: Connection closed by remote host
```

**Comment by LoisRForgeFlow** [comment]
@moylop260 Sorry for bothering you, but I'm back to this issue and I would like to move forward. Can you check my comment above: https://github.com/OCA/ddmrp/pull/17#issuecomment-410439787

Thanks in advance!

EDIT: Finally runbot is green! :smile:  but was trial and error I couldn't ever connet to it.

**Review by JordiBForgeFlow — APPROVED** [review]

**Pull request merged**
