### PR TITLE
[14.0] [MIG] ddmrp_adjustment

### PR DESCRIPTION
**Pull request by DavidBForgeFlow**
Standard migration to v14.

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@DavidBForgeFlow Base module has been merged, you can rebase this PR. Also have a look at your commit messages, the last two have the same msg.
image

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by GenisPForgeFlow — APPROVED** [review]
Functional Review

**Pull request merged**
