### PR TITLE
[13.0] Fix security on make procurement on stock buffer

### PR DESCRIPTION
**Pull request by jbaudoux**
Prevent any user to run a procurement. As the procurement is run as super user, no security check was performed and any user could run a procurement.
I added a restriction to users having write access on the buffer.
In our setup, we have different buffer profiles (distributed, purchased) managed by different user groups (resp. stock, purchase). Those have read access to all buffers but can only manage (write) their buffers. So I restrict procurement to only the buffer you manage (this explains why the restriction is on write and not read)

Remove obsolete requested_uid from context

cc @jgrandguillaume @LoisRForgeFlow

### CODE REVIEW

**Review by jgrandguillaume — APPROVED** [review]
For me this checks make sense so +1 

Not everyone able to read buffer should be able to create PO or logistic document. So I think this is usefule addition.

**Comment by JordiBForgeFlow** [comment]
@jbaudoux If you'd want to prevent some users from running procurements, the best approach IMHO would be to limit the access to the action to launch procurements, restricting the action to users in a certain group. What do you think @LoisRForgeFlow ?

**Comment by jgrandguillaume** [comment]
> @jbaudoux If you'd want to prevent some users from running procurements, the best approach IMHO would be to limit the access to the action to launch procurements, restricting the action to users in a certain group. What do you think @LoisRForgeFlow ?

Yes, that's a good idea too

**Comment by jbaudoux** [comment]
> @jbaudoux If you'd want to prevent some users from running procurements, the best approach IMHO would be to limit the access to the action to launch procurements, restricting the action to users in a certain group. What do you think @LoisRForgeFlow ?

The difficulty is that both purchase and stock must have access to the buffers. But stock users should not make purchase procurement (i.e. PO). And purchase users should not make internal warehouse replenishment.

**Comment by JordiBForgeFlow** [comment]
@jbaudoux then perhaps we need an explicit group "Create procurements from stock buffers"?

**Comment by JordiBForgeFlow** [comment]
@jbaudoux ahh, I see what you mean. Different users have separate permissions. Perhaps this is something that you should be able to solve through access rights? People from the warehouse perhaps shall not be able to display purchase buffers?

**Comment by jbaudoux** [comment]
> @jbaudoux ahh, I see what you mean. Different users have separate permissions. Perhaps this is something that you should be able to solve through access rights? People from the warehouse perhaps shall not be able to display purchase buffers?

We tried this but it appeared to be a bad idea because you need the full picture of the process chain to ensure no buffer are missing and the complete routing is there and consistent. So we gave read access to both user groups but restricted create/write/unlink access based on buffer profile (purchase/distributed)

**Comment by LoisRForgeFlow** [comment]
> > @jbaudoux ahh, I see what you mean. Different users have separate permissions. Perhaps this is something that you should be able to solve through access rights? People from the warehouse perhaps shall not be able to display purchase buffers?
> 
> We tried this but it appeared to be a bad idea because you need the full picture of the process chain to ensure no buffer are missing and the complete routing is there and consistent. So we gave read access to both user groups but restricted create/write/unlink access based on buffer profile (purchase/distributed)

This seems a good approach to not overcompliate it. So from my side, I have no problem with the change proposed in this PR, we can always improve it or make it more flexible/customizable in the future if needed.

**Comment by JordiBForgeFlow** [comment]
OK then! Good for me too!

**Review by LoisRForgeFlow — APPROVED** [review]

**Pull request merged**
