### PR TITLE
[17.0][MIG] ddmrp

### PR DESCRIPTION
**Pull request by DavidJForgeFlow**
Migration to version 17.0

Supersedes #447 

Depends on 
- https://github.com/OCA/web/pull/2846 
- https://github.com/OCA/stock-logistics-warehouse/pull/1959 

@ForgeFlow

### CODE REVIEW

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
An error raises when accesing the buffer list with debug=1

image

**Comment by DavidJForgeFlow** [comment]
> An error raises when accesing the buffer list with debug=1
> 
> image

Fixed!

**Review by LoisRForgeFlow — APPROVED** [review]
Looks good enough to merge, basic flows and screens works and look good. Let's see if we find moro issues as we progress in the migration

**Pull request merged**
