### PR TITLE
[14.0][FW] ddmrp: multiple ports from 13.0

### PR DESCRIPTION
**Pull request by nguyenhk99**
Port of the following PRs from 13.0 to 14.0:
* #61 
* #88

### CODE REVIEW

**Comment by TDu** [comment]
LG, thanks, not sure any changes from #81 are included, but not to worry.

**Comment by nguyenhk99** [comment]
> LG, thanks, not sure any changes from #81 are included, but not to worry.

Hello @TDu , PR #105 already has all commits of #81.

**Review by sebalix — CHANGES_REQUESTED** [review]
- The commit https://github.com/OCA/ddmrp/pull/179/commits/97df08d3e303ff46f2a59546abe7bc2aa3c0eb25 seems wrong, its sibling v13 one is here: https://github.com/OCA/ddmrp/pull/148/files
- As well as https://github.com/OCA/ddmrp/pull/179/commits/d0e1581cd9fea31ef59eb7f1e268f3b32dd3918e which doesn't reflect https://github.com/OCA/ddmrp/pull/160/files

Can you check?

**Comment by nguyenhk99** [comment]
> * The commit [97df08d](https://github.com/OCA/ddmrp/commit/97df08d3e303ff46f2a59546abe7bc2aa3c0eb25) seems wrong, its sibling v13 one is here: https://github.com/OCA/ddmrp/pull/148/files
> 
>     * As well as [d0e1581](https://github.com/OCA/ddmrp/commit/d0e1581cd9fea31ef59eb7f1e268f3b32dd3918e) which doesn't reflect https://github.com/OCA/ddmrp/pull/160/files
> 
> 
> Can you check?

Hi @sebalix. Thank you for the review. I see that we don't need these 2 commits and I removed them.

**Comment by sebalix** [comment]
@HoKhanhNguyen99 can you cherry-pick https://github.com/OCA/ddmrp/pull/177 too? It has been merged two days ago

**Comment by nguyenhk99** [comment]
> @HoKhanhNguyen99 can you cherry-pick #177 too? It has been merged two days ago

Sure @sebalix . I just pushed it.

**Review by sebalix — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM :+1:

**Pull request merged**
