### PR TITLE
[15.0][FIX] ddmrp: remove mrp_move.py as it is not used

### PR DESCRIPTION
**Pull request by BernatPForgeFlow**

### CODE REVIEW

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
Can you just remove all the file? I think it is dead code.

**Comment by BernatPForgeFlow** [comment]
> Can you just remove all the file? I think it is dead code.

@LoisRForgeFlow Done!

**Review by LoisRForgeFlow — APPROVED** [review]
Ty!

**Pull request merged**
