### PR TITLE
[13.0] ddmrp: add dependency on stock_helper

### PR DESCRIPTION
**Pull request by guewen**
See OCA/stock-logistics-warehouse#1073

### CODE REVIEW

**Review by simahawk — APPROVED** [review]
LG

**Comment by sebalix** [comment]
I removed the last commit bringing the test dependency now that OCA/stock-logistics-warehouse#1073 is merged.

**Review by sebalix — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
