### PR TITLE
[14.0][REF] ddmrp: Compute dlt depending on buffer location

### PR DESCRIPTION
**Pull request by BernatPForgeFlow**
When we compute DLT for manufactured buffers, we need to consider the location from where we are computing. If the buffered products change between one location and another, the DLTs will be different.

https://github.com/OCA/ddmrp/assets/90243017/0e46692d-4b84-4d9c-a38e-fdab8c5c82dd

Comments:
- Which location should have priority, the location of the BoM or the one passed by context? 
- It would be nice to add a feature in the BoM form that allows to change the context location.

### CODE REVIEW

**Review by LoisRForgeFlow — COMMENTED** [review]
This is looking good! I think the next step is to get rid of the mrp_bom_location dependency

**Comment by BernatPForgeFlow** [comment]
> This is looking good! I think the next step is to get rid of the mrp_bom_location dependency

I got rid of the mrp_bom_location dependency. WDYT?

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM :+1:

**Pull request merged**
