### PR TITLE
[13.0][FIX] ddmrp: reuse `_past_moves_domain` in yearly consuption action

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Attend https://github.com/OCA/ddmrp/pull/150#pullrequestreview-745051400.

@ForgeFlow

### CODE REVIEW

**Review by TDu — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
Issue fixed here https://github.com/OCA/maintainer-quality-tools/pull/695.

/ocabot merge patch

**Pull request merged**
