### PR TITLE
[13.0][FIX] ddmrp_warning: access warnings report multi-company environment

### PR DESCRIPTION
**Pull request by OriolMForgeFlow**
- Added rules to support multi-company in ddmrp_warning

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by JoanSForgeFlow — APPROVED** [review]
LGTM!

**Comment by LoisRForgeFlow** [comment]
@OriolMForgeFlow could you forwardport this change to 14.0 and 15.0?

**Pull request merged**
